"""Initial migration

Revision ID: 4f45cb98f1e0
Revises: a37d089fabac
Create Date: 2025-09-03 14:16:23.278464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f45cb98f1e0'
down_revision = 'a37d089fabac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###