"""Initial migration

Revision ID: a37d089fabac
Revises: 9577b76006cd
Create Date: 2025-09-03 14:11:38.573280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a37d089fabac'
down_revision = '9577b76006cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###